In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import random
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
from geopy.distance import geodesic
from sklearn.cluster import KMeans
import folium
import numpy as np

ModuleNotFoundError: No module named 'seaborn'

# 1. Data Preparation

## 1.1 Input Data

In [ ]:
# Load dataset
data = pd.read_csv(
     '../data/dataset_NYC.txt',
    sep='\t',
    header=None,
    encoding='ISO-8859-1',
    names=['User_ID', 'Venue_ID', 'Venue_Category_ID', 'Category_Name',
           'Latitude', 'Longitude', 'Timezone_Offset', 'UTC_Time'],
    dtype={
        'User_ID': 'str',
        'Venue_ID': 'str',
        'Venue_Category_ID': 'str',
        'Category_Name': 'category',
        'Latitude': 'float32',
        'Longitude': 'float32',
        'Timezone_Offset': 'int16',
        'UTC_Time': 'str'
    }
)

print(data.head())

  User_ID                  Venue_ID         Venue_Category_ID  \
0     470  49bbd6c0f964a520f4531fe3  4bf58dd8d48988d127951735
1     979  4a43c0aef964a520c6a61fe3  4bf58dd8d48988d1df941735
2      69  4c5cc7b485a1e21e00d35711  4bf58dd8d48988d103941735
3     395  4bc7086715a7ef3bef9878da  4bf58dd8d48988d104941735
4      87  4cf2c5321d18a143951b5cec  4bf58dd8d48988d1cb941735

         Category_Name   Latitude  Longitude  Timezone_Offset  \
0  Arts & Crafts Store  40.719810 -74.002579             -240
1               Bridge  40.606800 -74.044167             -240
2       Home (private)  40.716160 -73.883072             -240
3       Medical Center  40.745163 -73.982521             -240
4           Food Truck  40.740105 -73.989655             -240

                         UTC_Time
0  Tue Apr 03 18:00:09 +0000 2012
1  Tue Apr 03 18:00:25 +0000 2012
2  Tue Apr 03 18:02:24 +0000 2012
3  Tue Apr 03 18:02:41 +0000 2012
4  Tue Apr 03 18:03:00 +0000 2012

## 1.2 Data Cleaning

In [294]:
# Remove duplicates
data = data.drop_duplicates()
data.reset_index(drop=True, inplace=True)

# Handle missing values
data = data.dropna()

### Convert to Local Time

In [295]:
# Convert UTC time
data['UTC_Time'] = pd.to_datetime(data['UTC_Time'], format="%a %b %d %H:%M:%S %z %Y", errors='coerce')
data = data.dropna(subset=['UTC_Time'])

# Add timezone and local time
data['Timezone_Offset'] = pd.to_timedelta(data['Timezone_Offset'], unit='m')
data['Local_Time'] = data['UTC_Time'] + data['Timezone_Offset']

# Remove UTC label after applying the offset
data['Local_Time'] = data['Local_Time'].dt.tz_convert(None)

# Drop unnecessary columns
data = data.drop(columns=['UTC_Time', 'Timezone_Offset'])
 
data.head()

,User_ID,Venue_ID,Venue_Category_ID,Category_Name,Latitude,Longitude,Local_Time
0,470,49bbd6c0f964a520f4531fe3,4bf58dd8d48988d127951735,Arts & Crafts Store,40.719810,-74.002579,2012-04-03 14:00:09
1,979,4a43c0aef964a520c6a61fe3,4bf58dd8d48988d1df941735,Bridge,40.606800,-74.044167,2012-04-03 14:00:25
2,69,4c5cc7b485a1e21e00d35711,4bf58dd8d48988d103941735,Home (private),40.716160,-73.883072,2012-04-03 14:02:24
3,395,4bc7086715a7ef3bef9878da,4bf58dd8d48988d104941735,Medical Center,40.745163,-73.982521,2012-04-03 14:02:41
4,87,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck,40.740105,-73.989655,2012-04-03 14:03:00

## 1.3 Add Broader Categories

In [296]:
# Load category mapping
category_table = pd.read_csv('../data/categories.csv')

# Add missing categories dynamically if needed
missing_category = pd.DataFrame({
    'Category ID': ['4e51a0c0bd41d3446defbb2e'],
    'Category Name': ['Ferry'],
    'Category Label': ['Travel and Transportation > Ferry']
})
category_table = pd.concat([category_table, missing_category], ignore_index=True)

# Rename and merge
category_table.rename(columns={'Category ID': 'Venue_Category_ID'}, inplace=True)
data = data.merge(category_table, on='Venue_Category_ID', how='left')

# Extract broader categories
data['Broader_Category'] = data['Category Label'].str.split(' > ').str[0]
print(data[['Category_Name', 'Broader_Category']].head())

         Category_Name          Broader_Category
0  Arts & Crafts Store                    Retail
1               Bridge    Landmarks and Outdoors
2       Home (private)  Community and Government
3       Medical Center       Health and Medicine
4           Food Truck       Dining and Drinking

In [297]:
# Keep only the relevant columns
data = data.drop(columns=['Category Label','Category Name'])

# Check the cleaned data
print(data.head())

  User_ID                  Venue_ID         Venue_Category_ID  \
0     470  49bbd6c0f964a520f4531fe3  4bf58dd8d48988d127951735
1     979  4a43c0aef964a520c6a61fe3  4bf58dd8d48988d1df941735
2      69  4c5cc7b485a1e21e00d35711  4bf58dd8d48988d103941735
3     395  4bc7086715a7ef3bef9878da  4bf58dd8d48988d104941735
4      87  4cf2c5321d18a143951b5cec  4bf58dd8d48988d1cb941735

         Category_Name   Latitude  Longitude          Local_Time  \
0  Arts & Crafts Store  40.719810 -74.002579 2012-04-03 14:00:09
1               Bridge  40.606800 -74.044167 2012-04-03 14:00:25
2       Home (private)  40.716160 -73.883072 2012-04-03 14:02:24
3       Medical Center  40.745163 -73.982521 2012-04-03 14:02:41
4           Food Truck  40.740105 -73.989655 2012-04-03 14:03:00

           Broader_Category
0                    Retail
1    Landmarks and Outdoors
2  Community and Government
3       Health and Medicine
4       Dining and Drinking

In [ ]:
#Handle missing values: Check and impute or drop missing data if necessary.
print(data.isnull().sum())  # Check for missing values

# Inspect rows with missing Broader_Category
missing_broader_category = data[data['Broader_Category'].isnull()]
print(missing_broader_category[['Venue_Category_ID', 'Category_Name']])

User_ID              0
Venue_ID             0
Venue_Category_ID    0
Category_Name        0
Latitude             0
Longitude            0
Local_Time           0
Broader_Category     0
dtype: int64
Empty DataFrame
Columns: [Venue_Category_ID, Category_Name]
Index: []

In [ ]:
# Group by broader category
broader_analysis = data.groupby('Broader_Category').agg(
    Venue_Count=('Venue_ID', 'nunique'),
    User_Count=('User_ID', 'nunique'),
    Average_Latitude=('Latitude', 'mean'),
    Average_Longitude=('Longitude', 'mean')
).reset_index()

# Display the analysis
print(broader_analysis)

                     Broader_Category  Venue_Count  User_Count  \
0              Arts and Entertainment         2000        1017
1  Business and Professional Services         3527        1022
2            Community and Government         4347         979
3                 Dining and Drinking        13909        1080
4                 Health and Medicine          843         494
5              Landmarks and Outdoors         3111        1024
6                      Nightlife Spot           68          95
7                              Retail         5745        1064
8               Sports and Recreation          997         729
9           Travel and Transportation         3854        1045

   Average_Latitude  Average_Longitude
0         40.760483         -73.983269
1         40.752331         -73.984848
2         40.765167         -73.974915
3         40.749542         -73.977554
4         40.777157         -73.962959
5         40.752041         -73.963875
6         40.818882         -73.989594
7         40.762592         -73.981529
8         40.763744         -73.984421
9         40.740921         -73.960197

## 1.4 Feature Engineering

### Derive Temporal Features

In [ ]:
# Extract day of the week
data['Day_of_Week'] = data['Local_Time'].dt.day_name()

# Identify if the visit was on a weekend
data['Is_Weekend'] = data['Day_of_Week'].isin(['Saturday', 'Sunday']).astype(int)

# Extract hour to categorize the time of visit
data['Hour'] = data['Local_Time'].dt.hour

# Create time buckets (e.g., Morning, Afternoon, Evening, Night)
def time_bucket(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

data['Time_Bucket'] = data['Hour'].apply(time_bucket)

print(data[['Local_Time', 'Day_of_Week', 'Is_Weekend', 'Hour', 'Time_Bucket']].head())

           Local_Time Day_of_Week  Is_Weekend  Hour Time_Bucket
0 2012-04-03 14:00:09     Tuesday           0    14   Afternoon
1 2012-04-03 14:00:25     Tuesday           0    14   Afternoon
2 2012-04-03 14:02:24     Tuesday           0    14   Afternoon
3 2012-04-03 14:02:41     Tuesday           0    14   Afternoon
4 2012-04-03 14:03:00     Tuesday           0    14   Afternoon

### Create User Profiles

- Summarized user preferences:
  - Most frequently visited category (Category_Name_Preferred).
  - Most frequent time of visit (Time_Bucket_Preferred).

In [ ]:
# Most visited category for each user
user_top_category = (
    data.groupby(['User_ID', 'Category_Name'])
    .size()
    .reset_index(name='Visit_Count')
    .sort_values(['User_ID', 'Visit_Count'], ascending=[True, False])
    .drop_duplicates('User_ID')
)
data = data.merge(user_top_category[['User_ID', 'Category_Name']], on='User_ID', how='left', suffixes=('', '_Preferred'))

# Most frequent time bucket for each user
user_top_time = (
    data.groupby(['User_ID', 'Time_Bucket'])
    .size()
    .reset_index(name='Visit_Count')
    .sort_values(['User_ID', 'Visit_Count'], ascending=[True, False])
    .drop_duplicates('User_ID')
)
data = data.merge(user_top_time[['User_ID', 'Time_Bucket']], on='User_ID', how='left', suffixes=('', '_Preferred'))

/var/folders/nz/5xr642r54x3dn9ht717qh3780000gn/T/ipykernel_96966/98680036.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(['User_ID', 'Category_Name'])

In [302]:
data.head()

,User_ID,Venue_ID,Venue_Category_ID,Category_Name,Latitude,Longitude,Local_Time,Broader_Category,Day_of_Week,Is_Weekend,Hour,Time_Bucket,Category_Name_Preferred,Time_Bucket_Preferred
0,470,49bbd6c0f964a520f4531fe3,4bf58dd8d48988d127951735,Arts & Crafts Store,40.719810,-74.002579,2012-04-03 14:00:09,Retail,Tuesday,0,14,Afternoon,Gym / Fitness Center,Morning
1,979,4a43c0aef964a520c6a61fe3,4bf58dd8d48988d1df941735,Bridge,40.606800,-74.044167,2012-04-03 14:00:25,Landmarks and Outdoors,Tuesday,0,14,Afternoon,Beach,Afternoon
2,69,4c5cc7b485a1e21e00d35711,4bf58dd8d48988d103941735,Home (private),40.716160,-73.883072,2012-04-03 14:02:24,Community and Government,Tuesday,0,14,Afternoon,Home (private),Afternoon
3,395,4bc7086715a7ef3bef9878da,4bf58dd8d48988d104941735,Medical Center,40.745163,-73.982521,2012-04-03 14:02:41,Health and Medicine,Tuesday,0,14,Afternoon,Office,Morning
4,87,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck,40.740105,-73.989655,2012-04-03 14:03:00,Dining and Drinking,Tuesday,0,14,Afternoon,Office,Afternoon

### Venue Popularity
- Compute venue popularity based on visit frequency.
- Normalize popularity to range between 0 and 1 for comparison.

In [ ]:
# Compute venue popularity
venue_popularity = data.groupby('Venue_ID')['User_ID'].count().reset_index(name='totalVisits')

# Normalize popularity
venue_popularity['Popularity_Score'] = venue_popularity['totalVisits'] / venue_popularity['totalVisits'].max()

# Merge popularity back into the main dataset
data = data.merge(venue_popularity[['Venue_ID', 'Popularity_Score']], on='Venue_ID', how='left')
data = data.merge(venue_popularity[['Venue_ID', 'totalVisits']], on='Venue_ID', how='left')

print(data[['Venue_ID', 'totalVisits' , 'Popularity_Score']].head())

                   Venue_ID  totalVisits  Popularity_Score
0  49bbd6c0f964a520f4531fe3           33          0.028821
1  4a43c0aef964a520c6a61fe3          134          0.117031
2  4c5cc7b485a1e21e00d35711          104          0.090830
3  4bc7086715a7ef3bef9878da            2          0.001747
4  4cf2c5321d18a143951b5cec           10          0.008734

In [304]:
# Count visits per venue and time bucket
venue_time_bucket_visits = data.groupby(['Venue_ID', 'Time_Bucket']).size().reset_index(name='Visit_Count')
print(venue_time_bucket_visits.head())

# Identify the most popular time bucket for each venue
venue_top_time_bucket = venue_time_bucket_visits.sort_values(['Venue_ID', 'Visit_Count'], ascending=[True, False])\
    .drop_duplicates('Venue_ID')\
    .rename(columns={'Time_Bucket': 'Busy_TimeBucket', 'Visit_Count': 'Max_Visit_Count'})

print(venue_top_time_bucket.head())

                   Venue_ID Time_Bucket  Visit_Count
0  3fd66200f964a52000e71ee3   Afternoon            1
1  3fd66200f964a52000e71ee3     Evening            8
2  3fd66200f964a52000e71ee3     Morning            1
3  3fd66200f964a52000e71ee3       Night            6
4  3fd66200f964a52000e81ee3   Afternoon            1
                    Venue_ID Busy_TimeBucket  Max_Visit_Count
1   3fd66200f964a52000e71ee3         Evening                8
4   3fd66200f964a52000e81ee3       Afternoon                1
6   3fd66200f964a52000f11ee3           Night                1
7   3fd66200f964a52001e51ee3           Night                1
10  3fd66200f964a52001e81ee3           Night                9

In [305]:
# Merge the most popular time bucket back into the main dataset
data = data.merge(venue_top_time_bucket[['Venue_ID', 'Busy_TimeBucket']], on='Venue_ID', how='left')
print(data[['Venue_ID', 'Category_Name', 'Busy_TimeBucket']].head(10))

                   Venue_ID        Category_Name Busy_TimeBucket
0  49bbd6c0f964a520f4531fe3  Arts & Crafts Store       Afternoon
1  4a43c0aef964a520c6a61fe3               Bridge         Evening
2  4c5cc7b485a1e21e00d35711       Home (private)           Night
3  4bc7086715a7ef3bef9878da       Medical Center       Afternoon
4  4cf2c5321d18a143951b5cec           Food Truck       Afternoon
5  4b5b981bf964a520900929e3    Food & Drink Shop       Afternoon
6  4ab966c3f964a5203c7f20e3          Coffee Shop       Afternoon
7  4d0cc47f903d37041864bf55          Bus Station         Morning
8  4ce1863bc4f6a35d8bd2db6c       Home (private)         Evening
9  4be319b321d5a59352311811                 Bank       Afternoon

In [306]:
data.head()

,User_ID,Venue_ID,Venue_Category_ID,Category_Name,Latitude,Longitude,Local_Time,Broader_Category,Day_of_Week,Is_Weekend,Hour,Time_Bucket,Category_Name_Preferred,Time_Bucket_Preferred,Popularity_Score,totalVisits,Busy_TimeBucket
0,470,49bbd6c0f964a520f4531fe3,4bf58dd8d48988d127951735,Arts & Crafts Store,40.719810,-74.002579,2012-04-03 14:00:09,Retail,Tuesday,0,14,Afternoon,Gym / Fitness Center,Morning,0.028821,33,Afternoon
1,979,4a43c0aef964a520c6a61fe3,4bf58dd8d48988d1df941735,Bridge,40.606800,-74.044167,2012-04-03 14:00:25,Landmarks and Outdoors,Tuesday,0,14,Afternoon,Beach,Afternoon,0.117031,134,Evening
2,69,4c5cc7b485a1e21e00d35711,4bf58dd8d48988d103941735,Home (private),40.716160,-73.883072,2012-04-03 14:02:24,Community and Government,Tuesday,0,14,Afternoon,Home (private),Afternoon,0.090830,104,Night
3,395,4bc7086715a7ef3bef9878da,4bf58dd8d48988d104941735,Medical Center,40.745163,-73.982521,2012-04-03 14:02:41,Health and Medicine,Tuesday,0,14,Afternoon,Office,Morning,0.001747,2,Afternoon
4,87,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck,40.740105,-73.989655,2012-04-03 14:03:00,Dining and Drinking,Tuesday,0,14,Afternoon,Office,Afternoon,0.008734,10,Afternoon

### Geographic Features
- Calculate the average latitude and longitude for each user to estimate their preferred region.
- Compute the distance of venues from the user’s central location.

In [307]:
# Compute user's average latitude and longitude
user_location_center = data.groupby('User_ID')[['Latitude', 'Longitude']].mean().reset_index()
user_location_center.rename(columns={'Latitude': 'Avg_Latitude', 'Longitude': 'Avg_Longitude'}, inplace=True)

# Merge user's central location into the main dataset
data = data.merge(user_location_center, on='User_ID', how='left')

# Compute distance from the user's central location
from haversine import haversine, Unit

# Vectorized computation of distances
data['Distance_From_Center'] = data.apply(
    lambda row: haversine(
        (row['Avg_Latitude'], row['Avg_Longitude']),
        (row['Latitude'], row['Longitude']),
        unit=Unit.KILOMETERS
    ), axis=1
)

In [308]:
print(data[['User_ID', 'Venue_ID', 'Distance_From_Center']].head())
print(data.nsmallest(10,'Distance_From_Center'))

  User_ID                  Venue_ID  Distance_From_Center
0     470  49bbd6c0f964a520f4531fe3              3.416134
1     979  4a43c0aef964a520c6a61fe3              2.544965
2      69  4c5cc7b485a1e21e00d35711              0.440875
3     395  4bc7086715a7ef3bef9878da              0.965516
4      87  4cf2c5321d18a143951b5cec              0.892979
       User_ID                  Venue_ID         Venue_Category_ID  \
102490      59  4c2b99aab34ad13a0f0beace  4bf58dd8d48988d118951735
103596      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
108749      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
113227      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
114953      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
117802      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
122588      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
123173      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
125194      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735
126196      14  4c83a1e451ada1cd8c332710  4bf58dd8d48988d1e0931735

            Category_Name   Latitude  Longitude          Local_Time  \
102490  Food & Drink Shop  40.750458 -73.877586 2012-06-09 15:40:09
103596        Coffee Shop  40.741905 -73.989067 2012-06-10 08:27:29
108749        Coffee Shop  40.741905 -73.989067 2012-06-13 15:18:39
113227        Coffee Shop  40.741905 -73.989067 2012-06-18 12:16:12
114953        Coffee Shop  40.741905 -73.989067 2012-06-21 10:39:05
117802        Coffee Shop  40.741905 -73.989067 2012-07-02 09:07:12
122588        Coffee Shop  40.741905 -73.989067 2012-07-05 18:33:11
123173        Coffee Shop  40.741905 -73.989067 2012-07-06 08:00:41
125194        Coffee Shop  40.741905 -73.989067 2012-07-07 19:11:24
126196        Coffee Shop  40.741905 -73.989067 2012-07-08 15:02:12

           Broader_Category Day_of_Week  Is_Weekend  Hour Time_Bucket  \
102490               Retail    Saturday           1    15   Afternoon
103596  Dining and Drinking      Sunday           1     8     Morning
108749  Dining and Drinking   Wednesday           0    15   Afternoon
113227  Dining and Drinking      Monday           0    12   Afternoon
114953  Dining and Drinking    Thursday           0    10     Morning
117802  Dining and Drinking      Monday           0     9     Morning
122588  Dining and Drinking    Thursday           0    18     Evening
123173  Dining and Drinking      Friday           0     8     Morning
125194  Dining and Drinking    Saturday           1    19     Evening
126196  Dining and Drinking      Sunday           1    15   Afternoon

       Category_Name_Preferred Time_Bucket_Preferred  Popularity_Score  \
102490                Building               Morning          0.000873
103596                    Park               Morning          0.041048
108749                    Park               Morning          0.041048
113227                    Park               Morning          0.041048
114953                    Park               Morning          0.041048
117802                    Park               Morning          0.041048
122588                    Park               Morning          0.041048
123173                    Park               Morning          0.041048
125194                    Park               Morning          0.041048
126196                    Park               Morning          0.041048

        totalVisits Busy_TimeBucket  Avg_Latitude  Avg_Longitude  \
102490            1       Afternoon     40.750500     -73.877602
103596           47       Afternoon     40.741856     -73.989067
108749           47       Afternoon     40.741856     -73.989067
113227           47       Afternoon     40.741856     -73.989067
114953           47       Afternoon     40.741856     -73.989067
117802           47       Afternoon     40.741856     -73.989067
122588           47       Afternoon     40.741856     -73.989067
123173           47       Afternoon     40.741856     -73.989067
125194           47       Afternoon     40.741856     -73.989067
126196           47       Afternoon     40.741856     -73.989067

        Distance_From_Center
102490              0.004840
103596              0.005514
108749              0.005514
113227              0.005514
114953              0.005514
117802              0.005514
122588              0.005514
123173              0.005514
125194              0.005514
126196              0.005514

In [309]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227178 entries, 0 to 227177
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   User_ID                  227178 non-null  object
 1   Venue_ID                 227178 non-null  object
 2   Venue_Category_ID        227178 non-null  object
 3   Category_Name            227178 non-null  category
 4   Latitude                 227178 non-null  float32
 5   Longitude                227178 non-null  float32
 6   Local_Time               227178 non-null  datetime64[ns]
 7   Broader_Category         227178 non-null  object
 8   Day_of_Week              227178 non-null  object
 9   Is_Weekend               227178 non-null  int64
 10  Hour                     227178 non-null  int32
 11  Time_Bucket              227178 non-null  object
 12  Category_Name_Preferred  227178 non-null  category
 13  Time_Bucket_Preferred    227178 non-null  object
 14  Popularity_Score         227178 non-null  float64
 15  totalVisits              227178 non-null  int64
 16  Busy_TimeBucket          227178 non-null  object
 17  Avg_Latitude             227178 non-null  float32
 18  Avg_Longitude            227178 non-null  float32
 19  Distance_From_Center     227178 non-null  float64
dtypes: category(2), datetime64[ns](1), float32(4), float64(2), int32(1), int64(2), object(8)
memory usage: 27.8+ MB
None

### Create Profiles

In [310]:
# Precompute user profiles
user_profiles = data.groupby('User_ID').agg(
    Preferred_Category=('Category_Name_Preferred', 'first'),
    Preferred_Time_Bucket=('Time_Bucket_Preferred', 'first'),
    Avg_Latitude=('Avg_Latitude', 'mean'),
    Avg_Longitude=('Avg_Longitude', 'mean')
    
).reset_index()

# Precompute venue profiles
venue_profiles = data.groupby('Venue_ID').agg(
    Popularity_Score=('Popularity_Score', 'mean'),
    Latitude=('Latitude', 'mean'),
    Longitude=('Longitude', 'mean')
).reset_index()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227178 entries, 0 to 227177
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   User_ID                  227178 non-null  object
 1   Venue_ID                 227178 non-null  object
 2   Venue_Category_ID        227178 non-null  object
 3   Category_Name            227178 non-null  category
 4   Latitude                 227178 non-null  float32
 5   Longitude                227178 non-null  float32
 6   Local_Time               227178 non-null  datetime64[ns]
 7   Broader_Category         227178 non-null  object
 8   Day_of_Week              227178 non-null  object
 9   Is_Weekend               227178 non-null  int64
 10  Hour                     227178 non-null  int32
 11  Time_Bucket              227178 non-null  object
 12  Category_Name_Preferred  227178 non-null  category
 13  Time_Bucket_Preferred    227178 non-null  object
 14  Popularity_Score         227178 non-null  float64
 15  totalVisits              227178 non-null  int64
 16  Busy_TimeBucket          227178 non-null  object
 17  Avg_Latitude             227178 non-null  float32
 18  Avg_Longitude            227178 non-null  float32
 19  Distance_From_Center     227178 non-null  float64
dtypes: category(2), datetime64[ns](1), float32(4), float64(2), int32(1), int64(2), object(8)
memory usage: 27.8+ MB

### Output Engineered Features

In [312]:
# Save the engineered dataset
#data.to_csv('../data/engineered_dataset.csv', index=False)

# Step 6: Recommendation System

## 1. Recommend 10 unvisited Locations

#### 1.1 Recommendations based on Userprofile

**Algorithm:**
- Retrieve Broader Category: For the input category_name, find its corresponding Broader_Category.
- Filter Venues: Include only venues that share the same broader category.
- Exclude Visited Venues: Remove venues the user has already visited.
- Score and Rank: Rank venues based on the calculated score.

In [313]:
def recommend_similar_category_locations(user_id, category_name, data, top_k=10):
    """
    Recommend unique venues of a similar category for a user.

    Args:
        user_id (str): User ID.
        category_name (str): The specific venue category to find similar categories.
        data (pd.DataFrame): Dataset with user and venue information.
        top_k (int): Number of recommendations to return.

    Returns:
        pd.DataFrame: Top recommended venues with scores.
    """
    # Normalize input category name
    category_name = category_name.lower()
    
    # Get the broader category for the input category
    try:
        broader_category = data.loc[
            data['Category_Name'].str.lower() == category_name, 'Broader_Category'
        ].values[0]
    except IndexError:
        raise ValueError(f"Category name '{category_name}' not found in the dataset.")
    
    # Filter data for venues in the broader category
    similar_venues = data[data['Broader_Category'] == broader_category]

    # Drop duplicate venues
    similar_venues = similar_venues.drop_duplicates(subset='Venue_ID')

    # Exclude venues already visited by the user
    visited = set(data[data['User_ID'] == user_id]['Venue_ID'])
    unvisited = similar_venues[~similar_venues['Venue_ID'].isin(visited)].copy()
    
    if unvisited.empty:
        return pd.DataFrame(columns=['Venue_ID', 'Category_Name', 'Score'])
    
    # Calculate scores based on popularity and proximity
    unvisited['Score'] = unvisited['Popularity_Score'] / (1 + unvisited['Distance_From_Center'])
    
    # Return the top-k unique venues
    return unvisited.nlargest(top_k, 'Score')[['Venue_ID', 'Category_Name', 'Score', 'Latitude', 'Longitude']]

##### Example Usage

In [ ]:
# Example usage of the recommendation function
user_id = '20'
category_name = 'Subway'
# Generate recommendations
recommendations = recommend_similar_category_locations(
    user_id=user_id,
    category_name=category_name,
    data=data,
    top_k=10
)
print(recommendations)

#Problem : 
# same recommendations each time with the same VenueID 
# User is supposed to input a Venue_Category_ID (maybe first check if there are different Category_IDs with the same Category_Name)

                       Venue_ID         Category_Name     Score   Latitude  \
167    42829c80f964a5206a221fe3         Train Station  0.710441  40.752808
552    42911d00f964a520f5231fe3         Train Station  0.320038  40.750793
389    4840fe6bf964a52030501fe3           Bus Station  0.233641  40.757221
445    4a4821f5f964a52095aa1fe3                  Road  0.218146  40.761169
137    4a737bf8f964a52091dc1fe3         Train Station  0.095176  40.707150
2832   4b837318f964a520a30631e3  Gas Station / Garage  0.084362  40.672874
33847  4afefbe2f964a5207b3222e3                 Ferry  0.057921  40.759449
1079   4d3e1b47557d6dcb4c484b44                  Road  0.057631  40.965351
103    43a52546f964a520532c1fe3               Airport  0.053173  40.645088
1177   4a0c2e7bf964a52014751fe3                 Hotel  0.052181  40.762245

       Longitude
167   -73.977173
552   -73.993576
389   -73.991547
445   -74.011292
137   -73.990570
2832  -73.870697
33847 -74.005623
1079  -74.062805
103   -73.784523
1177  -73.979286

#### 1.2 Recommendations based on similar users

**Collaborative Filtering**

#### 1.2.1. Construct the User-Category Matrix
user-item interaction matrix where:
- Rows represent users.
- Columns represent venues or categories.
- Values represent interaction strength (e.g., visit frequency or normalized score).

In [315]:
# Aggregate features at the User-Category level
user_category_features = data.groupby(['User_ID', 'Category_Name']).agg(
    total_visits=('totalVisits', 'sum'),
    avg_popularity=('Popularity_Score', 'mean'),
    weekend_visits=('Is_Weekend', 'sum'),
    avg_distance=('Distance_From_Center', 'mean')
).reset_index()

# Normalize numerical features to ensure fair weighting
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
user_category_features[['total_visits', 'avg_popularity', 'weekend_visits', 'avg_distance']] = scaler.fit_transform(
    user_category_features[['total_visits', 'avg_popularity', 'weekend_visits', 'avg_distance']]
)

# Create a pivot table
user_category_matrix = user_category_features.pivot_table(
    index='User_ID',
    columns='Category_Name',
    values=['total_visits', 'avg_popularity', 'weekend_visits', 'avg_distance'],
    fill_value=0
)

# Flatten multi-level columns for readability
user_category_matrix.columns = ['_'.join(col).strip() for col in user_category_matrix.columns]
print(user_category_matrix.head())

/var/folders/nz/5xr642r54x3dn9ht717qh3780000gn/T/ipykernel_96966/1534222941.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  user_category_features = data.groupby(['User_ID', 'Category_Name']).agg(
/var/folders/nz/5xr642r54x3dn9ht717qh3780000gn/T/ipykernel_96966/1534222941.py:18: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  user_category_matrix = user_category_features.pivot_table(

         avg_distance_Afghan Restaurant  avg_distance_African Restaurant  \
User_ID
1                                   0.0                              0.0
10                                  0.0                              0.0
100                                 0.0                              0.0
1000                                0.0                              0.0
1001                                0.0                              0.0

         avg_distance_Airport  avg_distance_American Restaurant  \
User_ID
1                    0.323900                          0.100439
10                   0.467233                          0.095215
100                  0.231046                          0.000000
1000                 0.000000                          0.000000
1001                 0.329415                          0.053867

         avg_distance_Animal Shelter  avg_distance_Antique Shop  \
User_ID
1                                0.0                        0.0
10                               0.0                        0.0
100                              0.0                        0.0
1000                             0.0                        0.0
1001                             0.0                        0.0

         avg_distance_Aquarium  avg_distance_Arcade  \
User_ID
1                     0.000000                  0.0
10                    0.000000                  0.0
100                   0.000000                  0.0
1000                  0.455241                  0.0
1001                  0.000000                  0.0

         avg_distance_Arepa Restaurant  avg_distance_Argentinian Restaurant  \
User_ID
1                                  0.0                                  0.0
10                                 0.0                                  0.0
100                                0.0                                  0.0
1000                               0.0                                  0.0
1001                               0.0                                  0.0

         ...  weekend_visits_Zoo  weekend_visits_Garden Center  \
User_ID  ...
1        ...                 0.0                           0.0
10       ...                 0.0                           0.0
100      ...                 0.0                           0.0
1000     ...                 0.0                           0.0
1001     ...                 0.0                           0.0

         weekend_visits_Market  weekend_visits_Military Base  \
User_ID
1                          0.0                           0.0
10                         0.0                           0.0
100                        0.0                           0.0
1000                       0.0                           0.0
1001                       0.0                           0.0

         weekend_visits_Newsstand  weekend_visits_Photography Lab  \
User_ID
1                             0.0                             0.0
10                            0.0                             0.0
100                           0.0                             0.0
1000                          0.0                             0.0
1001                          0.0                             0.0

         weekend_visits_Public Art  weekend_visits_Castle  \
User_ID
1                              0.0                    0.0
10                             0.0                    0.0
100                            0.0                    0.0
1000                           0.0                    0.0
1001                           0.0                    0.0

         weekend_visits_Music School  weekend_visits_Pet Service
User_ID
1                                0.0                         0.0
10                               0.0                         0.0
100                              0.0                         0.0
1000                             0.0                         0.0
1001                             0.0                         0.0

[5 rows x 1004 columns]

#### 1.2.2. Compute User Similarity

In [ ]:
# Compute cosine similarity between users
user_similarity = cosine_similarity(user_category_matrix)

# Convert similarity matrix to a DataFrame
user_similarity_df = pd.DataFrame(
    user_similarity, 
    index=user_category_matrix.index, 
    columns=user_category_matrix.index
)

print(user_similarity_df.head())

User_ID         1        10       100      1000      1001      1002      1003  \
User_ID
1        1.000000  0.418525  0.443328  0.047425  0.397440  0.159501  0.114458
10       0.418525  1.000000  0.371499  0.143007  0.412085  0.299409  0.102807
100      0.443328  0.371499  1.000000  0.038430  0.262777  0.187770  0.141071
1000     0.047425  0.143007  0.038430  1.000000  0.328168  0.199540  0.022472
1001     0.397440  0.412085  0.262777  0.328168  1.000000  0.286014  0.093820

User_ID      1004      1005      1006  ...       990       991       992  \
User_ID                                ...
1        0.559435  0.330126  0.045446  ...  0.209991  0.108572  0.344313
10       0.387974  0.433227  0.137103  ...  0.225525  0.244318  0.424955
100      0.392256  0.329646  0.127847  ...  0.179412  0.144347  0.365112
1000     0.108207  0.322047  0.053607  ...  0.000000  0.325104  0.320326
1001     0.288877  0.454309  0.078671  ...  0.144685  0.553804  0.432768

User_ID       993       994       995       996       997       998       999
User_ID
1        0.348398  0.446669  0.185360  0.199412  0.307613  0.043467  0.279518
10       0.335233  0.391848  0.176562  0.278078  0.348612  0.217789  0.186032
100      0.383720  0.318066  0.171194  0.305686  0.361840  0.104140  0.262908
1000     0.138805  0.324254  0.040599  0.037826  0.165506  0.443556  0.174987
1001     0.254926  0.855501  0.117956  0.094583  0.296398  0.600387  0.139584

[5 rows x 1083 columns]

#### 1.2.3. Recommendations based on similar users

In [3]:
def recommend_collaborative(user_id, category_name, data, user_similarity_df, user_category_matrix, top_k=10):
    """
    Recommend unvisited locations for a user based on collaborative filtering.

    Args:
        user_id (str): The target user ID.
        category_name (str): The specific category to find similar venues.
        data (pd.DataFrame): Dataset with user and venue information.
        user_similarity_df (pd.DataFrame): User similarity matrix.
        user_category_matrix (pd.DataFrame): User-category interaction matrix.
        top_k (int): Number of recommendations to return.

    Returns:
        pd.DataFrame: Top recommended venues.
    """
    # Find similar users
    similar_users = user_similarity_df.loc[user_id].sort_values(ascending=False).iloc[1:11].index
    

    # Filter data for the target category and similar users
    similar_user_venues = data[
        (data['User_ID'].isin(similar_users)) & 
        (data['Category_Name'] == category_name)
    ]

    # Exclude venues already visited by the target user
    visited_venues = set(data[data['User_ID'] == user_id]['Venue_ID'])
    unvisited = similar_user_venues[~similar_user_venues['Venue_ID'].isin(visited_venues)]

    # Aggregate scores by venue
    recommendations = unvisited.groupby('Venue_ID').agg(
        Popularity=('Popularity_Score', 'mean'),
        Latitude=('Latitude', 'first'),
        Longitude=('Longitude', 'first'),
        Category_Name=('Category_Name', 'first')
    ).reset_index()

    # Calculate scores (you can adjust weights for better personalization)
    recommendations['Score'] = recommendations['Popularity']
    return recommendations.nlargest(top_k, 'Score')

In [5]:
# Example usage
recommendations = recommend_collaborative(
    user_id='470',
    category_name='Bar',
    data=data,
    user_similarity_df=user_similarity_df,
    user_category_matrix=user_category_matrix,
    top_k=10
)

print(recommendations)

NameError: name 'data' is not defined

## 3. Recommend a place where 5 people can meet
Content-Based Filtering:
- Content-based filtering recommends venues by matching user preferences to venue features.

#### 3.1 User Profiles
Aggregate user preferences (e.g., favorite categories).

In [85]:
user_profiles = data.groupby('User_ID').agg({
    'Category_Name': lambda x: x.value_counts().idxmax(),  # Most visited category
    'Broader_Category': lambda x: x.value_counts().idxmax()  # Most visited broader category
}).reset_index()

#### 3.2 Match User Preferences

In [86]:
from geopy.distance import geodesic

def recommend_meeting_place(user_ids, data, top_k=3):
    """
    Recommend a meeting place for a group of users.
    Args:
        user_ids (list): List of user IDs.
        data (pd.DataFrame): Dataset with venue and user location information.
        top_k (int): Number of recommendations to return.
    Returns:
        pd.DataFrame: Recommended venues.
    """
    # Get user locations
    user_locations = data[data['User_ID'].isin(user_ids)][['Latitude', 'Longitude']]
    if user_locations.empty:
        raise ValueError("No locations found for the given user IDs.")
    
    # Compute group centroid
    centroid = user_locations.mean().values
    
    # Calculate distance of venues to the centroid
    data['Distance_To_Centroid'] = data.apply(
        lambda row: geodesic(centroid, (row['Latitude'], row['Longitude'])).km, axis=1
    )
    
    # Rank venues by proximity
    return data.nsmallest(top_k, 'Distance_To_Centroid')[['Venue_ID', 'Category_Name', 'Distance_To_Centroid']]

In [87]:
# Define 5 user IDs
user_ids = ['293', '294', '295', '296', '297']

# Recommend meeting place
meeting_place = recommend_meeting_place(user_ids, data, top_k=3)
print(meeting_place)

                        Venue_ID   Venue_Category_Name  Distance_To_Centroid
92743   4d93daa44f78f04d139decb9    Mexican Restaurant              0.019036
140857  4d93daa44f78f04d139decb9    Mexican Restaurant              0.019036
209982  4deb1ad118386283a3f7a316  Arts & Entertainment              0.022664

In [ ]:
# creating a folium_map function that displays restaurant lovations

def folium_map(data):
    """
    The function takes in a dataframe and using the latitude and longitude columns displays a map showing the locations of 
    all the restaurants available in the input data
    """
    # reseting the index in the input dataframe
    dff=data.reset_index(drop=True)


# Set up center latitude and longitude
    center_lat = dff['Latitude'][0]
    center_long = dff['Longitude'][0]

# Initialize map with center lat and long
    map_ =folium.Map([center_lat,center_long], zoom_start=7)

# Adjust this limit to see more or fewer businesses
    limit=dff.shape[0]
    print(f"{limit-1} Restaurant Locations")
    for index in range(limit-1):
        # Extract information about business
        lat = dff.loc[index,'latitude']
        long = dff.loc[index,'longitude']
        name = dff.loc[index,'name']
        rating = dff.loc[index,'b/s_rating']
        location = dff.loc[index,'location']
        details = "{}\nStars: {} {}".format(name,rating,location)

# Create popup with relevant details
        popup = folium.Popup(details,parse_html=True)

# Create marker with relevant lat/long and popup
        marker = folium.Marker(location=[lat,long], popup=popup)

        marker.add_to(map_)

    return display(map_)  # returning a map display

folium_map(data=data.loc[:10])

10 Restaurant Locations

KeyError: 'latitude'